# Generated by Django 2.1.4 on 2019-01-07 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1500)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 7, 6, 20, 37, 408447, tzinfo=utc), null=True)),
                ('written_by', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='Newscategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='newsportalapp.Newscategory'),
        ),
    ]
